# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# format = '[](bold blue) $all'


[line_break]
disabled = true

[cmd_duration]
disabled = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[ ](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol   = '[ ](bold red)'
vimcmd_symbol  = '[ ](bold yellow)'

[directory]
style = "bold yellow"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

scan_timeout = 300
