# Core Colors
background            #111415
foreground            #bfc8ca
cursor                #51d7ee
cursor_text_color     #00363e
selection_background  #334b4f
selection_foreground  #cde7ed

# Regular Colors
color0  #1d2021               
color1  #ffb4ab                 
color2  #51d7ee               
color3  #bcc5eb              
color4  #51d7ee  
color5  #b1cbd1
color6  #bcc5eb             
color7  #e1e3e3            

# Bright Colors
color8  #363a3a         
color9  #93000a                  
color10 #004e59                
color11 #3c4665               
color12 #51d7ee   
color13 #cde7ed 
color14 #dbe1ff              
color15 #e1e3e3             
