cursor_shape block
# window_padding_width 10 15
window_padding_width 10 15

shell_integration enabled
confirm_os_window_close 0

scrollbar hovered

# BEGIN_KITTY_SYMBOL_MAPS
symbol_map U+E000-U+E00A Symbols Nerd Font Mono
symbol_map U+E0A0-U+E0C8 Symbols Nerd Font Mono
symbol_map U+E0CA Symbols Nerd Font Mono
symbol_map U+E0CC-U+E0D7 Symbols Nerd Font Mono
symbol_map U+E200-U+E2A9 Symbols Nerd Font Mono
symbol_map U+E300-U+E3E3 Symbols Nerd Font Mono
symbol_map U+E5FA-U+E6B1 Symbols Nerd Font Mono
symbol_map U+E700-U+E7C5 Symbols Nerd Font Mono
symbol_map U+EA60-U+EBEB Symbols Nerd Font Mono
symbol_map U+ED00-U+EFC1 Symbols Nerd Font Mono
symbol_map U+F000-U+F2E0 Symbols Nerd Font Mono
symbol_map U+F300-U+F372 Symbols Nerd Font Mono
symbol_map U+F400-U+F533 Symbols Nerd Font Mono
symbol_map U+E000-U+F8FF,U+F0000-U+FFFFF,U+100000-U+10ffff JetBrainsMonoNL Nerd Font

# END_KITTY_SYMBOL_MAPS

text_composition_strategy platform
box_drawing_scale 0.001, 0.75, 1.5, 2

cursor_trail 1

include colors.conf

# Jump around neighboring window Vi key binding
map ctrl+shift+w>h neighboring_window left
map ctrl+shift+w>l neighboring_window right
map ctrl+shift+w>j neighboring_window down
map ctrl+shift+w>k neighboring_window up

map ctrl+shift+w>shift+h move_window left
map ctrl+shift+w>shift+l move_window right
map ctrl+shift+w>shift+j move_window down
map ctrl+shift+w>shift+k move_window up

# Create a new window, splitting the space used by the existing one so that
# the two windows are placed one above the other
map ctrl+shift+w>s launch --location=hsplit

# Create a new window, splitting the space used by the existing one so that
# the two windows are placed side by side
map ctrl+shift+w>v launch --location=vsplit

# Use nvim as the pager. Remove all ASCII formatting characters.
scrollback_pager nvim -u ~/.config/nvim-scrollback/init.lua -n -c 'silent! %s/\%x1b\[[0-9;]*[sumJK]//g' -c 'silent! %s/\%x1b]133;[A-Z]\%x1b\\//g' -c 'silent! %s/\%x1b\[[^m]*m//g' -c 'silent! %s///g' -


# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Bold features='zero ss02 cv04 cv16 cv18 cv19 cv20'
italic_font      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-LightItalic features='zero ss02 cv04 cv16 cv18 cv19 cv20'
bold_italic_font family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-BoldItalic features='zero ss02 cv04 cv16 cv18 cv19 cv20'

font_size        11.5
# END_KITTY_FONTS


# BEGIN_KITTY_SYMBOL_MAPS
symbol_map U+E000-U+F8FF,U+F0000-U+FFFFF,U+100000-U+10ffff JetBrainsMonoNL Nerd Font
# END_KITTY_SYMBOL_MAPS

allow_remote_control yes
copy_on_select yes
