general {
    lock_cmd = echo "skip lock"        # không chạy hyprlock
    before_sleep_cmd = echo "skip lock"
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

listener {
    timeout = 200
    on-timeout = hyprctl dispatch dpms off    # tắt màn hình thay vì khóa
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

# listener {
#     timeout = 1800
#     on-timeout = systemctl suspend            # nếu muốn suspend vẫn giữ
# }
